# Assignment 1

## Task 1: A list of dictionaries

In [1]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

### Part a

In [2]:
valid_transactions = [
    x for x in transactions if 
        x["price"] != 0 and x["quantity"] >= 0
]

print(valid_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC'}]

### Part b

In [3]:
for t in valid_transactions:
    t["total"] = t["price"] * t["quantity"]

print(valid_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}]

### Part c

In [4]:
region_rev = {}

for t in valid_transactions:
    region = t["region"]
    revenue = t["total"]

    # Check if there is any region. 
    # The first occurrence of a region therefore results in its revenue.
    # The following occurrences result in the sum of its revenue and the existing amount. 
   
    if region in region_rev:
        region_rev[region] += revenue
    else:
        region_rev[region] = revenue

print(region_rev)

{'EU': 3600, 'US': 1050, 'APAC': 750}

### Part d

In [5]:
high_region = max(region_rev, key = region_rev.get)  
high_revenue = region_rev[high_region]

print(f"{high_region} has the highest revenue: {high_revenue}")

EU has the highest revenue: 3600

## Task 2: Creating a function

In [6]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

In [7]:
def summarise_sales(N):
    total = sum(N)
    average = round(sum(N)/len(N), 2)
    best_day = N.index(max(N)) + 1    #plus 1 because index starts at 0, day starts at 1
    worst_day = N.index(min(N)) + 1
    above_average_count = sum(1 for i in N if i > average)

    return {
        "total" : total,
        "average" : average,
        "best_day" : best_day,
        "worst_day" : worst_day,
        "above_average_count" : above_average_count
    }

print(summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}

## Task 3: Loop

In [8]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

### Part a

In [9]:
passing = [ i for i in students
    if i["grade"] >= 50
]

print(passing)

[{'name': 'Anna', 'grade': 85, 'attendance': 0.92}, {'name': 'Erik', 'grade': 58, 'attendance': 0.75}, {'name': 'Mia', 'grade': 91, 'attendance': 0.98}, {'name': 'Sara', 'grade': 72, 'attendance': 0.88}, {'name': 'Tom', 'grade': 67, 'attendance': 0.7}, {'name': 'Nina', 'grade': 95, 'attendance': 0.99}, {'name': 'Olli', 'grade': 50, 'attendance': 0.65}]

### Part b

In [10]:
for i in students:
    if i["grade"] >= 80:
        print(f"{i["name"]}: Excellent"),
    elif 50 < i["grade"] < 79:
        print(f"{i["name"]}: Pass"),
    else:
        print(f"{i["name"]}: Fail")

Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Fail

### Part c

In [11]:
print(sum(1 for i in students if i["attendance"] < 0.80))

4

### Part d

In [12]:
highest = students[0]

for i in students:
  if i["grade"] > highest["grade"]:
    highest = i
   
print(highest["name"] , highest["grade"])

Nina 95

### Part e

In [13]:
highest = max( students, key = lambda x : x["grade"])

for i in students:
    if i == highest:
        print(i["name"] , i["grade"])

Nina 95

## Task 4: Class and Methods

In [14]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    # Part a
    def add_asset(self, ticker, shares, price_per_share):
        self.holdings[ticker] = {
            "shares": shares,
            "price_per_share": price_per_share
        }

    # Part b
    def total_value(self):
        total = 0
        for data in self.holdings.values():  
            total += data["shares"] * data["price_per_share"]
        return total

    # Part c
    def most_valuable(self):
        return max(
            self.holdings,
            key=lambda t: self.holdings[t]["shares"] * self.holdings[t]["price_per_share"]
        )

    # Part d
    def __str__(self):
        return (f"Portfolio of {self.owner}, "
                f"Assets: {len(self.holdings)}, "
                f"Total value: €{self.total_value()}")

p = Portfolio("Minh Anh")

p.add_asset("AAPL", 10, 150)
p.add_asset("GOOGL", 5, 2800)
p.add_asset("TSLA", 8, 900)

print(p) 

print("Most valuable asset:", p.most_valuable())

Portfolio of Minh Anh, Assets: 3, Total value: €22700
Most valuable asset: GOOGL

## Task 5 Importing a module

In [15]:
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

In [16]:
import datetime

dates = [datetime.datetime.strptime(d, "%Y-%m-%d").date() for d,_ in orders]

difference = (max(dates)-min(dates)).days

print(difference)

80

## Task 6: Array Operations and Broadcasting

In [17]:
import numpy as np

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

### Part a

In [18]:
total = np.sum(revenue, axis = 1)

print(total)

[ 880  950 1080]

### Part b

In [19]:
mean = np.mean(revenue, axis = 0)

print(mean)

[226.66666667 260.         206.66666667 276.66666667]

### Part c

In [20]:
growth = np.array([1.05, 1.03, 1.08, 1.02])

adjusted_2024 = revenue[2] * growth
print(adjusted_2024)

[262.5 298.7 248.4 316.2]

### Part d

In [21]:
over_250 = revenue[revenue > 250]
print(over_250)

[260 270 290 310]

## Task 7

In [22]:
data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

### Part a

In [23]:
import pandas as pd
data = pd.DataFrame(data)

data["salary_per_year_exp"] = (data["salary"] / data["years_exp"]).round(0).astype(int)

print(data)

  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2
1     Erik  Marketing    4000          3                3.8
2      Mia    Finance    4800          7                4.5
3      Leo         IT    5200         10                4.0
4     Sara  Marketing    3900          2                3.5
5      Tom         IT    5100          8                4.9

   salary_per_year_exp
0                  900
1                 1333
2                  686
3                  520
4                 1950
5                  638

### Part b

In [24]:
data = data.sort_values(by = "performance_score" , ascending = False)

data.head(3)

,employee,department,salary,years_exp,performance_score,salary_per_year_exp
5,Tom,IT,5100,8,4.9,638
2,Mia,Finance,4800,7,4.5,686
0,Anna,Finance,4500,5,4.2,900

### Part c

In [25]:
data.loc[data["performance_score"] > 4.0]

,employee,department,salary,years_exp,performance_score,salary_per_year_exp
5,Tom,IT,5100,8,4.9,638
2,Mia,Finance,4800,7,4.5,686
0,Anna,Finance,4500,5,4.2,900

### Part d

In [26]:
data.rename(columns = {"years_exp" : "experience_years"})

,employee,department,salary,experience_years,performance_score,salary_per_year_exp
5,Tom,IT,5100,8,4.9,638
2,Mia,Finance,4800,7,4.5,686
0,Anna,Finance,4500,5,4.2,900
3,Leo,IT,5200,10,4.0,520
1,Erik,Marketing,4000,3,3.8,1333
4,Sara,Marketing,3900,2,3.5,1950

### Part e

In [27]:
data.iloc[0:4 , [2,4]]

   salary  performance_score
5    5100                4.9
2    4800                4.5
0    4500                4.2
3    5200                4.0

## Task 8: More Pandas

In [28]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

### Part a

In [29]:
data = {
    "date" : days,
    "visitors" : visitors,
    "conversion_rate" : conversion_rate,
    "avg_order_value" : avg_order_value
}

data = pd.DataFrame(data)
data.set_index("date" , inplace = True)

### Part b

In [30]:
data["conversions"] = (data["visitors"] * data["conversion_rate"]).round(0)
data["daily_revenue"] = data["conversions"] * data["avg_order_value"]

print(data)

            visitors  conversion_rate  avg_order_value  conversions  \
date
2025-01-06       206           0.0645            64.30         13.0
2025-01-07       472           0.0578            48.44         27.0
2025-01-08       437           0.0756            43.26         33.0
2025-01-09       221           0.0339            43.61          7.0
2025-01-10       563           0.0679            49.39         38.0
2025-01-11       288           0.0511            46.07         15.0
2025-01-12       302           0.0339            72.90         10.0
2025-01-13       273           0.0300            42.82          8.0
2025-01-14       333           0.0499            50.33         17.0
2025-01-15       270           0.0550            50.28         15.0
2025-01-16       339           0.0311            50.28         11.0
2025-01-17       524           0.0209            50.55         11.0
2025-01-18       380           0.0483            45.18         18.0
2025-01-19       569           0.0637            44.17         36.0
2025-01-20       379           0.0751            41.38         28.0
2025-01-21       310           0.0575            35.12         18.0
2025-01-22       515           0.0750            52.16         39.0
2025-01-23       527           0.0719            59.84         38.0
2025-01-24       544           0.0331            44.57         18.0
2025-01-25       555           0.0720            44.41         40.0
2025-01-26       210           0.0638            46.84         13.0
2025-01-27       405           0.0367            45.39         15.0
2025-01-28       307           0.0678            35.64         21.0
2025-01-29       297           0.0719            63.65         21.0
2025-01-30       296           0.0380            54.39         11.0
2025-01-31       529           0.0516            42.88         27.0
2025-02-01       516           0.0243            52.97         13.0
2025-02-02       285           0.0550            45.62         16.0

            daily_revenue
date
2025-01-06         835.90
2025-01-07        1307.88
2025-01-08        1427.58
2025-01-09         305.27
2025-01-10        1876.82
2025-01-11         691.05
2025-01-12         729.00
2025-01-13         342.56
2025-01-14         855.61
2025-01-15         754.20
2025-01-16         553.08
2025-01-17         556.05
2025-01-18         813.24
2025-01-19        1590.12
2025-01-20        1158.64
2025-01-21         632.16
2025-01-22        2034.24
2025-01-23        2273.92
2025-01-24         802.26
2025-01-25        1776.40
2025-01-26         608.92
2025-01-27         680.85
2025-01-28         748.44
2025-01-29        1336.65
2025-01-30         598.29
2025-01-31        1157.76
2025-02-01         688.61
2025-02-02         729.92